### ISSUE TITLE
Commit to gh-pages branch by default

### ISSUE THREAD

**Issue by stefnotch** [htl-leonding-college/asciidoctor-docker-template#2]
It'd be neat if [this script](https://github.com/htl-leonding-college/asciidoctor-docker-template/blob/master/publish-gh-pages.sh) would switch to the `gh-pages` branch, commit and push the files there and then switch back. 

That way, autogenerated files won't clutter the git history.

**Comment by stefnotch** [comment]
Redirect script
```html
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="refresh" content="1;url=leonie-web-demo/index.html">
        <title>Page Redirection</title>
    </head>
    <body>
        If you are not redirected automatically, <a href="leonie-web-demo/index.html">click here</a>

		<!-- TODO: Links to the other versions of Leonie -->
    </body>
</html>
```

**Comment by stefnotch** [comment]
Leaving everything on the master branch in the current config is rather troublesome, because it really clutters up everything.

**Comment by stefnotch** [comment]
Apparently the usual way of doing this is [something like this](https://blog.bloomca.me/2017/12/15/how-to-push-folder-to-github-pages.html). It basically force pushes a folder to the gh-pages branch. 

[Here in an npm package which does exactly that](https://www.npmjs.com/package/gh-pages)

**Comment by htl-leonding** [comment]
Thank you for this suggestion. The link was great. All is working now. The gh-pages are in an own branch now. I removed the scripts for pdf and slides. The pdf skript will return after refactoring, for the slides I will create a new repo.
